import { AnimalBody, PageInfo, ResponseBody } from '../services/types';

export const testPageInfo: PageInfo = {
    pageNumber: 1,
    pageSize: 9,
    numberOfElements: 19,
    totalElements: 19,
    totalPages: 3,
    firstPage: false,
    lastPage: false,
};

export const testAnimals: AnimalBody[] = [
    {
        uid: '1',
        name: 'Test animal',
        earthAnimal: true,
        earthInsect: false,
        avian: true,
        canine: false,
        feline: true,
    },
    {
        uid: '2',
        name: 'Test animal 2',
        earthAnimal: false,
        earthInsect: true,
        avian: false,
        canine: true,
        feline: false,
    },
    {
        uid: '3',
        name: 'Test animal 3',
        earthAnimal: true,
        earthInsect: false,
        avian: true,
        canine: false,
        feline: true,
    },
    {
        uid: '4',
        name: 'Test animal 4',
        earthAnimal: true,
        earthInsect: false,
        avian: true,
        canine: false,
        feline: true,
    },
    {
        uid: '5',
        name: 'Test animal 5',
        earthAnimal: true,
        earthInsect: false,
        avian: true,
        canine: false,
        feline: true,
    },
    {
        uid: '6',
        name: 'Test animal 6',
        earthAnimal: true,
        earthInsect: false,
        avian: true,
        canine: false,
        feline: true,
    },
    {
        uid: '7',
        name: 'Test animal 7',
        earthAnimal: true,
        earthInsect: false,
        avian: true,
        canine: false,
        feline: true,
    },
    {
        uid: '8',
        name: 'Test animal 8',
        earthAnimal: true,
        earthInsect: false,
        avian: true,
        canine: false,
        feline: true,
    },
    {
        uid: '10',
        name: 'Test animal 10',
        earthAnimal: true,
        earthInsect: false,
        avian: true,
        canine: false,
        feline: true,
    },
    {
        uid: '11',
        name: 'Test animal 11',
        earthAnimal: true,
        earthInsect: false,
        avian: true,
        canine: false,
        feline: true,
    },
    {
        uid: '12',
        name: 'Test animal 12',
        earthAnimal: true,
        earthInsect: false,
        avian: true,
        canine: false,
        feline: true,
    },
    {
        uid: '13',
        name: 'Test animal 13',
        earthAnimal: true,
        earthInsect: false,
        avian: true,
        canine: false,
        feline: true,
    },
    {
        uid: '14',
        name: 'Test animal 14',
        earthAnimal: true,
        earthInsect: false,
        avian: true,
        canine: false,
        feline: true,
    },
    {
        uid: '15',
        name: 'Test animal 15',
        earthAnimal: true,
        earthInsect: false,
        avian: true,
        canine: false,
        feline: true,
    },
    {
        uid: '16',
        name: 'Test animal 16',
        earthAnimal: true,
        earthInsect: false,
        avian: true,
        canine: false,
        feline: true,
    },
    {
        uid: '17',
        name: 'Test animal 17',
        earthAnimal: true,
        earthInsect: false,
        avian: true,
        canine: false,
        feline: true,
    },
    {
        uid: '18',
        name: 'Test animal 18',
        earthAnimal: true,
        earthInsect: false,
        avian: true,
        canine: false,
        feline: true,
    },
    {
        uid: '19',
        name: 'Test animal 19',
        earthAnimal: true,
        earthInsect: false,
        avian: true,
        canine: false,
        feline: true,
    },
];

export const testResponseBody: ResponseBody = {
    page: testPageInfo,
    sort: {
        clauses: [],
    },
    animals: testAnimals,
};

export const padeId = 1;

export const mockNavigate = vi.fn();
